use coffee_sim_core::Vec3;

pub(crate) mod conservation;
pub(crate) mod metrics;
pub(crate) mod profiler;

pub(crate) use conservation::ConservationLedger;
pub(crate) use metrics::{MetricsSnapshot, METRICS_SLOT_COUNT};
pub(crate) use profiler::{PassTimings, Profiler};

#[derive(Clone, Copy, Debug)]
pub(crate) struct WaterDiagnostics {
    pub all_finite: bool,
    pub sim_time_s: f32,
    pub active_count: u32,
    pub pool_count: u32,
    pub active_mass: f32,
    pub active_mass_ml: f32,
    pub emitted_ml: f32,
    pub rest_volume_ml: f32,
    pub current_volume_ml: f32,
    pub mean_j: f32,
    pub kinetic_energy: f32,
    pub rms_speed: f32,
    pub vertical_rms_speed: f32,
    pub mean_vertical_speed: f32,
    pub lateral_rms_speed: f32,
    pub max_speed: f32,
    pub max_upward_speed: f32,
    pub max_downward_speed: f32,
    pub upward_momentum: f32,
    pub downward_momentum: f32,
    pub vertical_dipole: Vec3,
    pub vertical_dipole_magnitude: f32,
    pub momentum: Vec3,
    pub momentum_magnitude: f32,
    pub centroid: Vec3,
    pub min: Vec3,
    pub max: Vec3,
    pub extent: Vec3,
    pub surface_bin_count: u32,
    pub surface_possible_bins: u32,
    pub surface_mean_y: f32,
    pub surface_rms_y: f32,
    pub surface_min_y: f32,
    pub surface_max_y: f32,
    pub surface_peak_to_peak_y: f32,
    pub surface_tilt: Vec3,
    pub surface_tilt_magnitude: f32,
    pub surface_tilt_height_y: f32,
    pub surface_residual_rms_y: f32,
    pub surface_residual_peak_to_peak_y: f32,
    pub hydrostatic_sample_count: u32,
    pub hydrostatic_depth_m: f32,
    pub hydrostatic_top_pressure_pa: f32,
    pub hydrostatic_bottom_pressure_pa: f32,
    pub hydrostatic_delta_pressure_pa: f32,
    pub hydrostatic_gradient_pa_per_m: f32,
    pub hydrostatic_bottom_higher: bool,
    pub dissolved_solute_mass: f32,
    pub mean_tds: f32,
    pub cup_water_mass: f32,
    pub cup_solute_mass: f32,
    pub cup_tds: f32,
    pub extraction_yield: f32,
}

impl Default for WaterDiagnostics {
    fn default() -> Self {
        Self {
            all_finite: true,
            sim_time_s: 0.0,
            active_count: 0,
            pool_count: 0,
            active_mass: 0.0,
            active_mass_ml: 0.0,
            emitted_ml: 0.0,
            rest_volume_ml: 0.0,
            current_volume_ml: 0.0,
            mean_j: 1.0,
            kinetic_energy: 0.0,
            rms_speed: 0.0,
            vertical_rms_speed: 0.0,
            mean_vertical_speed: 0.0,
            lateral_rms_speed: 0.0,
            max_speed: 0.0,
            max_upward_speed: 0.0,
            max_downward_speed: 0.0,
            upward_momentum: 0.0,
            downward_momentum: 0.0,
            vertical_dipole: Vec3::ZERO,
            vertical_dipole_magnitude: 0.0,
            momentum: Vec3::ZERO,
            momentum_magnitude: 0.0,
            centroid: Vec3::ZERO,
            min: Vec3::ZERO,
            max: Vec3::ZERO,
            extent: Vec3::ZERO,
            surface_bin_count: 0,
            surface_possible_bins: 0,
            surface_mean_y: 0.0,
            surface_rms_y: 0.0,
            surface_min_y: 0.0,
            surface_max_y: 0.0,
            surface_peak_to_peak_y: 0.0,
            surface_tilt: Vec3::ZERO,
            surface_tilt_magnitude: 0.0,
            surface_tilt_height_y: 0.0,
            surface_residual_rms_y: 0.0,
            surface_residual_peak_to_peak_y: 0.0,
            hydrostatic_sample_count: 0,
            hydrostatic_depth_m: 0.0,
            hydrostatic_top_pressure_pa: 0.0,
            hydrostatic_bottom_pressure_pa: 0.0,
            hydrostatic_delta_pressure_pa: 0.0,
            hydrostatic_gradient_pa_per_m: 0.0,
            hydrostatic_bottom_higher: false,
            dissolved_solute_mass: 0.0,
            mean_tds: 0.0,
            cup_water_mass: 0.0,
            cup_solute_mass: 0.0,
            cup_tds: 0.0,
            extraction_yield: 0.0,
        }
    }
}
